#!/usr/bin/env bash
set -ex

sudo apt install git

wget -qO - richardsnider.github.io/vscode | bash

wget -qO - richardsnider.github.io/docker | bash

wget -q0 - richardsnider.github.io/git-ssh | bash

wget -qO - richardsnider.github.io/nodejs | bash

wget -qO - richardsnider.github.io/aws-cli | bash
